# Generated by Django 3.1.7 on 2021-04-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0002_auto_20210402_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.CharField(default='placeholder', max_length=100, verbose_name='product_image'),
        ),
    ]
